language: node_js
node_js: 6.10
before_script: npm install --dev
script:
- npm run lint
- npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages